---
language: python
python: "2.7"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r requirements.txt

script:
  - cookiecutter --version
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - cd test_project
  - ansible-playbook tests/test.yml -i tests/inventory -l localhost --connection=local -vvvv
  - bundle install
  - bundle exec rake spec SPEC_TARGET=localhost
